# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoTestChatBot' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'AWSCognito'
  pod 'AWSLex'
  pod 'RxSwift'
  pod 'RxCocoa'

  # Pods for DemoTestChatBot
  

end
